export { default as InputNascimentDate } from './InputNascimentDate'
export { default as InputName } from './InputName'
export { default as InputEmail } from './InputEmail'

export { default as InputGender } from './InputGender'
export { default as InputPassword } from './InputPassword'
export { default as InputTextArea } from './InputTextArea'
export { default as SearchSquare } from './SearchSquare'
export { default as QuizForm } from './QuizForm'
export { default as InputOtherText } from './InputOtherText'
